version: '3.8'

services:
  frontend:
    build:
      context: ./wiki-hackathon
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./wiki-hackathon:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./wiki-backend
      dockerfile: Dockerfile
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - PYTHONPATH=/app
      - NODE_ENV=development
    volumes:
      - ./wiki-backend:/app