version: '3.8'

services:
  frontend:
    build:
      context: ./wiki-hackathon
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./wiki-hackathon:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./wiki-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./wiki-backend:/app
      - /app/venv 